# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aster_cpp <- function(matrix, tree_width = 0L, proc = 1L, s = 0, n = 0L, ss = 0L) {
    .Call('BNSL_aster_cpp', PACKAGE = 'BNSL', matrix, tree_width, proc, s, n, ss)
}

aster_cpp_p <- function(matrix, psl, tree_width = 0L, proc = 1L, s = 0, n = 0L, ss = 0L) {
    .Call('BNSL_aster_cpp_p', PACKAGE = 'BNSL', matrix, psl, tree_width, proc, s, n, ss)
}

gc <- function(n, a) {
    .Call('BNSL_gc', PACKAGE = 'BNSL', n, a)
}

gc_all <- function(cc, a) {
    .Call('BNSL_gc_all', PACKAGE = 'BNSL', cc, a)
}

kruskal <- function(W) {
    .Call('BNSL_kruskal', PACKAGE = 'BNSL', W)
}

empirical_mi <- function(x, y) {
    .Call('BNSL_empirical_mi', PACKAGE = 'BNSL', x, y)
}

mi <- function(x, y, proc = 0L) {
    .Call('BNSL_mi', PACKAGE = 'BNSL', x, y, proc)
}

MDL_mi <- function(x, y, m_x = 0L, m_y = 0L) {
    .Call('BNSL_MDL_mi', PACKAGE = 'BNSL', x, y, m_x, m_y)
}

Jeffreys_mi <- function(x, y, m_x = 0L, m_y = 0L) {
    .Call('BNSL_Jeffreys_mi', PACKAGE = 'BNSL', x, y, m_x, m_y)
}

BDeu_mi <- function(x, y, m_x = 0L, m_y = 0L, d = 1) {
    .Call('BNSL_BDeu_mi', PACKAGE = 'BNSL', x, y, m_x, m_y, d)
}

empirical_cmi <- function(x, y, z) {
    .Call('BNSL_empirical_cmi', PACKAGE = 'BNSL', x, y, z)
}

cmi <- function(x, y, z, proc = 0L) {
    .Call('BNSL_cmi', PACKAGE = 'BNSL', x, y, z, proc)
}

MDL_cmi <- function(x, y, z, m_x = 0L, m_y = 0L, m_z = 0L) {
    .Call('BNSL_MDL_cmi', PACKAGE = 'BNSL', x, y, z, m_x, m_y, m_z)
}

Jeffreys_cmi <- function(x, y, z, m_x = 0L, m_y = 0L, m_z = 0L) {
    .Call('BNSL_Jeffreys_cmi', PACKAGE = 'BNSL', x, y, z, m_x, m_y, m_z)
}

BDeu_cmi <- function(x, y, z, m_x = 0L, m_y = 0L, m_z = 0L, d = 1) {
    .Call('BNSL_BDeu_cmi', PACKAGE = 'BNSL', x, y, z, m_x, m_y, m_z, d)
}

mi_matrix <- function(df, proc = 0L) {
    .Call('BNSL_mi_matrix', PACKAGE = 'BNSL', df, proc)
}

cont_mi <- function(x, y) {
    .Call('BNSL_cont_mi', PACKAGE = 'BNSL', x, y)
}

intervals <- function(level, array) {
    .Call('BNSL_intervals', PACKAGE = 'BNSL', level, array)
}

binary_search <- function(array, pattern) {
    .Call('BNSL_binary_search', PACKAGE = 'BNSL', array, pattern)
}

parent <- function(df0, h, tw = 0L, proc = 0L) {
    .Call('BNSL_parent', PACKAGE = 'BNSL', df0, h, tw, proc)
}

fftable <- function(df, w) {
    .Call('BNSL_fftable', PACKAGE = 'BNSL', df, w)
}

Bayes_score <- function(T, m, proc = 0L, s = 0, n = 0L, ss = 0L) {
    .Call('BNSL_Bayes_score', PACKAGE = 'BNSL', T, m, proc, s, n, ss)
}

Jeffreys_score <- function(T, m) {
    .Call('BNSL_Jeffreys_score', PACKAGE = 'BNSL', T, m)
}

MDL_score <- function(T, m, s, n) {
    .Call('BNSL_MDL_score', PACKAGE = 'BNSL', T, m, s, n)
}

BDeu_score <- function(T, m, ss) {
    .Call('BNSL_BDeu_score', PACKAGE = 'BNSL', T, m, ss)
}

bound <- function(T, m, proc = 0L, n = 0L, ss = 1L) {
    .Call('BNSL_bound', PACKAGE = 'BNSL', T, m, proc, n, ss)
}

Jeffreys_bound <- function(T, m) {
    .Call('BNSL_Jeffreys_bound', PACKAGE = 'BNSL', T, m)
}

quotient_Jeffreys_bound <- function(T, m, n, ss) {
    .Call('BNSL_quotient_Jeffreys_bound', PACKAGE = 'BNSL', T, m, n, ss)
}

MDL_bound <- function(T, m, n, ss) {
    .Call('BNSL_MDL_bound', PACKAGE = 'BNSL', T, m, n, ss)
}

BDeu_bound <- function(T, m) {
    .Call('BNSL_BDeu_bound', PACKAGE = 'BNSL', T, m)
}

